import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Collections",
  description: "Generated by create next app",
};
export default async function page() {
  return <div>Collections theo chain</div>;
}
