import React from "react";
import { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Collections",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
      <h1>Tất cả Collections</h1>
      {/* Ví dụ: danh sách chain */}
      <ul>
        <li>
          <Link href="/collections/base">Base Chain</Link>
        </li>
        <li>
          <Link href="/collections/ethereum">Ethereum Chain</Link>
        </li>
      </ul>
    </div>
  );
}
