import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Collections",
  description: "Generated by create next app",
};

export default function page() {
  return <div>Tất cả collections</div>;
}
