import Home from "@/features/home/Home";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <>
      <Home></Home>
    </>
  );
}
