// import Home from "@/components/home";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <div>
      page home
      {/* <Home></Home> */}
    </div>
  );
}
