services:
  shared:
    build:
      context: ./shared
      dockerfile: Dockerfile
    volumes:
      - shared_dist:/app/dist
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  consul:
    image: hashicorp/consul:latest
    command: "consul agent -dev -client=0.0.0.0"
    ports:
      - "8500:8500"
    volumes:
      - consul_data:/consul/data
    networks:
      - app-network

  auth-service:
    build:
      context: . # Context là project-root/ để bao gồm shared
      dockerfile: services/auth-service/Dockerfile
    depends_on:
      - rabbitmq
      - redis
      - consul
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    networks:
      - app-network

  user-service:
    build:
      context: . # Context là project-root/ để bao gồm shared
      dockerfile: services/user-service/Dockerfile
    depends_on:
      - rabbitmq
      - redis
      - consul
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    networks:
      - app-network

  api-gateway:
    build:
      context: . # Context là project-root/ để bao gồm shared
      dockerfile: api-gateway/Dockerfile
    depends_on:
      - auth-service
      - user-service
      - rabbitmq
      - redis
      - consul
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  rabbitmq_data:
  redis_data:
  consul_data:
  shared_dist:

networks:
  app-network:
    driver: bridge
