import React from "react";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Collections",
  description: "Generated by create next app",
};
export default async function page({ params }: { params: { chains: string } }) {
  const { chains } = await params;
  return <div>CollectionsPage {chains}</div>;
}
