import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Chain",
  description: "Generated by create next app",
};
export default function ChainPage() {
  return (
    <>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla nemo illo
      voluptates quod similique non, at asperiores beatae fugiat tenetur modi
      autem iusto, consequatur possimus eius quidem voluptatem? Odit, vero?
    </>
  );
}
