import Home from "@/features/home/Home";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Chain",
  description: "Generated by create next app",
};
export default function ChainPage() {
  return (
    <>
      <Home />
    </>
  );
}
