import React from "react";
import { Metadata } from "next";
import Collections from "@/features/collections/Collections";
export const metadata: Metadata = {
  title: "Collections",
  description: "Generated by create next app",
};
export default async function page({
  params,
}: {
  params: { chain: string; address: string };
}) {
  const { chain, address } = await params;

  return (
    <div>
      <p>Chain: {chain}</p>
      <p>Address: {address}</p>
      <Collections></Collections>
    </div>
  );
}
