import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>page admin</div>
  )
}
